[package]
name = "host"
version = "0.1.0"
edition = "2024"

[dependencies]
tss-esapi = { version = "7.7", default-features = false }
blake2 = { version = "0.10.6", default-features = false }
rpassword = "7.5.4"
zeroize = "1.9.0"
chacha20 = { version = "0.10.1", default-features = false, features = [
  "cipher",
  "rng",
] }
x25519-dalek = { version = "3.0.0", default-features = false, features = [
  "zeroize",
] }
termios = "0.3.3"
getrandom = "0.4.3"
